# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be305ed830d16212909264865331330fd8c91418021939c8bfe0168d4e9b34d93396248c0d5d62848e21e212f25c09af1e7f5a16589560b56c699dacfe0ed0ab

test:
  secret_key_base: f0d4d878de4210130f80155512a8cf00b007071c511369f25cb6cc74bad9bc8de8448c043135836f581125dc1b865403714cbda3065ca711a7c4cf7ce6350bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
